# Generated by Django 4.0.4 on 2022-06-05 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cloudzone', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NonSmokingArea',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('area_id', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=50)),
                ('area_detail', models.CharField(max_length=50)),
                ('city', models.CharField(max_length=50)),
                ('sigungu', models.CharField(max_length=50)),
                ('eupmyundong', models.CharField(max_length=50)),
                ('category', models.CharField(max_length=50)),
                ('reason', models.CharField(max_length=50)),
                ('area_size', models.FloatField()),
                ('fine', models.CharField(max_length=50)),
                ('address_doromyung', models.CharField(max_length=50)),
                ('address_jibeon', models.CharField(max_length=50)),
                ('manage_office', models.CharField(max_length=50)),
                ('latitude', models.DecimalField(decimal_places=8, default=0, max_digits=12)),
                ('longitude', models.DecimalField(decimal_places=8, default=0, max_digits=12)),
                ('image', models.CharField(max_length=50)),
                ('radius', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='SmokingArea',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('area_id', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=50)),
                ('area_detail', models.CharField(max_length=50)),
                ('city', models.CharField(max_length=50)),
                ('sigungu', models.CharField(max_length=50)),
                ('eupmyundong', models.CharField(max_length=50)),
                ('area_size', models.FloatField()),
                ('address_doromyung', models.CharField(max_length=50)),
                ('address_jibeon', models.CharField(max_length=50)),
                ('manage_office', models.CharField(max_length=50)),
                ('latitude', models.DecimalField(decimal_places=8, default=0, max_digits=12)),
                ('longitude', models.DecimalField(decimal_places=8, default=0, max_digits=12)),
                ('image', models.CharField(max_length=50)),
                ('radius', models.FloatField()),
            ],
        ),
    ]
