# Generated by Django 4.0.4 on 2022-06-05 10:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cloudzone', '0003_test'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Test',
        ),
    ]
