# Generated by Django 4.0.4 on 2022-06-05 11:35

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cloudzone', '0004_delete_test'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mannerrr',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', django.contrib.gis.db.models.fields.GeometryField(max_length=50, srid=4326)),
            ],
        ),
    ]
